# Generated by Django 5.2.10 on 2026-03-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_class_faculty_timetable_and_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyalert',
            name='recognized_persons',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
